# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release

on:
  workflow_dispatch: {}

jobs:
  android_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - name: 🔧 Build APK
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_FILE_BASE64: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        run: base64 -d <<< $ANDROID_STORE_FILE_BASE64 > android/app/release-key.jks && echo "storePassword="$ANDROID_STORE_PASSWORD >> android/key.properties && echo "keyPassword="$ANDROID_KEY_PASSWORD >> android/key.properties && echo "keyAlias="$ANDROID_KEY_ALIAS >> android/key.properties && echo "storeFile=release-key.jks" >> android/key.properties && flutter build apk --split-per-abi
        
       # && echo "storePassword="$ANDROID_STORE_PASSWORD >> android/key.properties && echo "keyPassword="$ANDROID_KEY_PASSWORD >> android/key.properties && echo "keyAlias="$ANDROID_KEY_ALIAS >> android/key.properties && echo "storeFile=release-key.jks" >> android/key.properties && cat android/key.properties && flutter build apk --split-per-abi

      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code-coverage-report
      #     path: build/app/outputs/flutter-apk/*.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: build/app/outputs/flutter-apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
